name: Build and publich NGINX docker images.

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./nginx/mainline-alma9.2.dockerfile
            context: ./nginx
            image: pfaffk/nginx
            tags: |
              type=raw,value=mainline-alma9.2
              type=raw,value=mainline-alma9.2-{{date 'YYYYMMDD'}}


    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          labels: |
            maintainer=Kamil Pfaff
            org.opencontainers.image.title=alma-nginx
          tags: ${{ matrix.tags }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
